name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "${{ matrix.pymc-version }} on py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]
        pymc-version: ["pymc3==3.8", "pymc3>=3.9,<3.10"]
        include:
          - python-version: "3.8"
            pymc-version: "https://github.com/pymc-devs/pymc3/archive/master.zip"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      # Setup
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install "${{ matrix.pymc-version }}"
          python -m pip install -U -e .[test]
          python -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          python -c 'import theano; print(theano.config.__str__(print_doc=False))'

      - name: Run tests
        shell: bash -l {0}
        run: python -m pytest --cov=pymc3_ext -v tests

      - name: Coveralls
        uses: exoplanet-dev/coveralls-python-action@develop
        continue-on-error: true
        with:
          parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: exoplanet-dev/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: true
